### ISSUE TITLE
2.1.1 Mostrar mapa del país

### ISSUE THREAD

**Issue by crperalta** [AlexViatela899/MemoriasHistoricas#15]
Yo como usuario aprendiz, deseo ver el mapa del país para identificar las principales zonas de  conflicto.

Criterios de aceptación.
[] Mostrar en pantalla mapa del país.
[] Mostrar sombreadas las zonas principales de conflicto armado.

**Comment by AlexViatela899** [comment]
Se realiza el mapa interactivo de Colombia.
