### ISSUE TITLE
2.1.2 Mostrar descripción para una zona de estudio seleccionada

### ISSUE THREAD

**Issue by crperalta** [AlexViatela899/MemoriasHistoricas#16]
Yo como usuario aprendiz, deseo ver una descripción breve al seleccionar la zona de estudio.

Criterios de aceptación
[] Reproducir contenido multimedia con la descripción de la zona de estudio.

**Comment by AlexViatela899** [comment]
Cada departamento despliega una imagen con datos clave de este
